### PR TITLE
syntax improvement on menu-bridges

### PR DESCRIPTION
**Pull request by nyxnor**
* `case` instead of elif for clarity
* get PING_SERVER domain with less commands
* `! -z` for non zero or not null and `-z` for zero/null
* `cat` is for concatenation, so there is no need to redirect with ">>"
* for loop on TACA dinamycally without elif, comparing range of numbers `[1-5]`

### CODE REVIEW

**Comment by nyxnor** [comment]
I did only on menu-bridges because that was what I was looking at the moment and it was a lot of changed lines, even though it was not edited a lot, that is how git perceives it.
If this is approved, then other menus will fit in the same criteria.

**Comment by radio24** [comment]
Thanks for your work.
I will rebase it to the v.0.4.3 branch because that's the current developer branch, not the master.

**Comment by radio24** [comment]
I checked the `menu-bridges` script. Changing from `elif` to `case` would mean that all other menus has also to be changed. Also, in the coming version, the `menu` script will be called by another external script - I know that it will work with the `elif` structure, but I'm not sure if this will work as intended with the `case` variant. 

Could you explain me the benefits of the `case` variant over the `elif` one?

**Comment by nyxnor** [comment]
they are the same thing but different structure.
Case statement is easy to differentiate between the menu options.
```sh
if [ $choice = 1 ]; then echo X
elif [ $choice = 2 ]; then echo Y
elif [ $choice = 3 ]; then echo Z
else then exit
fi
```
now compare with this:
```
case $choice in
  1) echo X;;
  2) echo Y;;
  3) echo Z;;
  *) exit
```

**Comment by radio24** [comment]
I agree with you. Did you intensely test the changed script?

Regarding the `menu` script: with v.0.4.3, the `first-use` script interacts with the `menu` script. It has to be tested if it does it correctly if the `menu` script is changed from the `elif` to the `case` structure.

**Comment by nyxnor** [comment]
Tested now, it works.

for the `menu`, had to use `CHOICE=$(echo "$CHOICE" | tr -d ' ')` to compare choices with `10)`, `11)`, not with `" 10)"`, " 11)".

**Comment by nyxnor** [comment]
hey, I commiting to the other menus now...

**Pull request merged**
