### PR TITLE
Vanguards

### PR DESCRIPTION
**Pull request by nyxnor**
Issue https://github.com/radio24/TorBox/issues/72

### CODE REVIEW

**Comment by radio24** [comment]
Thank you very much, nyxnor. I will look into it in the next days.

**Comment by nyxnor** [comment]
The official deb package use this for vanguards.service
```bash
[Unit]
Description=Additional protections for Tor onion services
After=network.target tor.service
Documentation=man:vanguards(1)

[Service]
User=debian-tor
Group=debian-tor
Environment=VANGUARDS_CONFIG=/etc/tor/vanguards.conf
ExecStart=/usr/bin/vanguards
Restart=always

[Install]
WantedBy=multi-user.target
```
I do not like `After=tor.service` cause restarting just tor@defaul.service and letting tor.service failed will break, so I prefer `After=tor@default.service`.

**Comment by nyxnor** [comment]
Ok, there is the Control Password too to configure https://github.com/mikeperry-tor/vanguards/blob/10942de93f6578f8303f60014f34de2fca345545/vanguards-example.conf#L25, how should I treat that best?

**Comment by radio24** [comment]
> Ok, there is the Control Password too to configure https://github.com/mikeperry-tor/vanguards/blob/10942de93f6578f8303f60014f34de2fca345545/vanguards-example.conf#L25, how should I treat that best?
> new_ident as typing every time or just letting it already written. As this is a .conf, letting it written is easier when restarting the service by any means.

Yes, for now, you can treat it like in new_ident. Put the default password into the file, and add in the Configuration menu entry 3 the following (adapted) code:

`sudo sed -i "s/^control_pass =.*/${INPUT}/" vanguards.conf`

**Comment by nyxnor** [comment]
Finished vanguards.

**Pull request merged**
